multikeys/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import static
from multikeys import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usradmin.urls')),
    path('system/', include('system.urls'))

]

urlpatterns += static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

system/urls.py
from django.urls import path
from . import views

app_name = 'system'

urlpatterns = [
    path('main.html', views.main),
    path('free.html', views.free),
    path('config.html', views.config),
    path('configed.html', views.configed),
    path('template.html', views.template),
    path('newtemp.html', views.new_temp),
    path('task.html', views.task),
    path('task_edit.html', views.task_edit),
    path('usradmin.html', views.usr_admin),
    path('createip.html', views.save_ip),
    path('log_user.html', views.log_user),
    path('log_system.html', views.log_system),

    path('configedaction', views.conf_action),
    path('saveTemplate', views.save_temp),
    path('deployTemplate', views.deploy_temp),
    path('deleteTemplate', views.delete_temp),
    path('tempAction', views.temp_action),
    path('loadtemp', views.loadtemp),
    path('getTempDetail', views.get_temp_detail),
    path('saveTask', views.task_save),
    path('deleteTask', views.task_delete),
    path('deployTask', views.task_deploy),
    path('saveconf', views.saveconf),
    path('getinfo', views.getinfo),
    path('getconfig', views.getconfig),
    path('configStatus', views.config_status),
    path('checkClient', views.check_client),
    path('connectStatus', views.connect_status),
    path('serverStatus', views.server_status),
    path('getStatus', views.get_status),
    path('getServerUsage', views.getServerUsage),
    path('tcpStatus', views.tcpstatus),
    path('devices', views.devices),
    path('ipConflict', views.ip_conflict),
    path('consumeMsg', views.consume_msg),
    path('userLogDownload', views.user_log_download),
    path('sysLogDownload', views.sys_log_download),
    # path('updateChannel', views.update_channel),
    path('getLogInfo', views.get_log_info),
    path('synData',views.synData)
]

usradmin/urls.py
from django.urls import path
from . import views

app_name ='usradmin'

urlpatterns = [
    path('', views.login, name='login'),

]

system/models.py
from django.db import models

# Create your models here.

system/forms.py
import hashlib
import sqlite3
from multikeys import settings
from django import forms
import STPython

database = settings.DATABASES

class ConfigForm(forms.Form):
    id = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'true'}), required=False)
    name = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'true'}), required=False)
    ip = forms.CharField(widget=forms.TextInput(attrs={'placeholder': '必填项', 'class': 'single_line'}), required=True)
    description = forms.CharField(widget=forms.TextInput(attrs={'class': 'single_line'}), required=False)
    key1 = forms.CharField(widget=forms.TextInput(attrs={'class': 'single_line'}), required=False)
    key2 = forms.CharField(widget=forms.TextInput(attrs={'class': 'single_line'}), required=False)
    key3 = forms.CharField(widget=forms.TextInput(attrs={'class': 'single_line'}), required=False)
    key4 = forms.CharField(widget=forms.TextInput(attrs={'class': 'single_line'}), required=False)
    key5 = forms.CharField(widget=forms.TextInput(attrs={'class': 'single_line'}), required=False)
    key6 = forms.CharField(widget=forms.TextInput(attrs={'class': 'single_line'}), required=False)
    key7 = forms.CharField(widget=forms.TextInput(attrs={'class': 'single_line'}), required=False)
    key8 = forms.CharField(widget=forms.TextInput(attrs={'class': 'single_line'}), required=False)
    key9 = forms.CharField(widget=forms.TextInput(attrs={'class': 'single_line'}), required=False)
    key10 = forms.CharField(widget=forms.TextInput(attrs={'class': 'single_line'}), required=False)
    key11 = forms.CharField(widget=forms.TextInput(attrs={'class': 'single_line'}), required=False)
    key12 = forms.CharField(widget=forms.TextInput(attrs={'class': 'single_line'}), required=False)
    status = forms.CharField(widget=forms.TextInput(attrs={'class': 'single_line'}), required=False)


class UsrForm(forms.Form):
    usrname = forms.CharField(label='用户名', max_length=100)
    old_password = forms.CharField(widget=forms.PasswordInput, label='原密码', max_length=100)
    new_password = forms.CharField(widget=forms.PasswordInput, label='新密码', max_length=100)
    new_password_confirm = forms.CharField(widget=forms.PasswordInput, label='新密码', max_length=100)
    def clean(self):
        old_password = self.cleaned_data['old_password']
        new_password = self.cleaned_data['new_password']
        new_password_confirm = self.cleaned_data['new_password_confirm']
        if(new_password == old_password):
            raise forms.ValidationError(u"新密码与原密码相同，请重新输入")
        elif(new_password != new_password_confirm):
            raise forms.ValidationError(u"两次输入的新密码不一致，请重新输入")
        m = old_password + "{{sdtzzq}}"
        pw = hashlib.md5(m.encode())
        conn = STPython.connect(user=database['default']['NAME'], password=database['default']['PASSWD'], dsn=database['default']['DSN'])
        cursor = conn.cursor()
        sql = " SELECT * FROM usradmin "
        cursor.execute(sql)
        val = cursor.fetchall()
        mpw = val[0][2]
        if (mpw == pw.hexdigest()):
            pass
        else:
             raise forms.ValidationError(u"原密码错误，请重新输入")
        conn.close()
        return self.cleaned_data


class IpForm(forms.Form):
    """
    这里是闫翔宇做的deMO，
    实现的功能是配置ip 端口号的功能
    """
    ip = forms.CharField(widget=forms.TextInput(attrs={ 'class': 'single_line'}), label='ip', required=True)
    description = forms.CharField(widget=forms.TextInput(attrs={'class': 'single_line'}), label='端口', required=True)
    user = forms.CharField(widget=forms.TextInput(attrs={'class': 'single_line'}), label='USER', required=True)
    password = forms.CharField(widget=forms.TextInput(attrs={'class': 'single_line'}), label='PASSWORD', required=True)
    dns = forms.CharField(widget=forms.TextInput(attrs={'placeholder': '000.000.000.000:00000/XXXXXX', 'class': 'single_line'}), label='DSN', required=True)
    model = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'XX.XXVIEW', 'class': 'single_line'}),label='MODEL', required=True)

system/views.py
# coding=utf-8
import os
import re
import psutil
import requests
import json
import hashlib
import sqlite3
import STPython
import logging
import queue
import configparser

from multikeys import settings
from .forms import ConfigForm
from .forms import UsrForm
from .forms import IpForm
from django.shortcuts import render
from django.contrib import messages
from django.http import JsonResponse
from django.http import FileResponse
from django.http import HttpResponseRedirect

# Create your views here.
msgQueue = queue.Queue(0)
database = settings.DATABASES
http_timeout = 2  #与终端的HTTP连接超时时间

status_dict = {}

#创建数据库
conn = STPython.connect(user=database['default']['NAME'], password=database['default']['PASSWD'], dsn=database['default']['DSN'])
cursor = conn.cursor()

sql = "SELECT RELNAME FROM sys_class WHERE RELKIND='r'"
cursor.execute(sql)
array = cursor.fetchall()
tabel1 = ('USRADMIN',)
tabel2 = ('INPUT_SELECT',)
tabel3 = ('OUTPUT_LIST',)
tabel4 = ('KEYS_SET',)
tabel5 = ('TEMPLATE',)
tabel6 = ('TASK',)
tabel7 = ('WEB_STATUS',)

global syndatamark
syndatamark = 0

#判断USRADMIN是否存在，如果不存在创建
if tabel1 in array:
    pass
else:
    cursor.execute('create table usradmin (id integer PRIMARY KEY AUTO_INCREMENT,username text,passwd text)')
    conn.commit()
    cursor.execute('INSERT INTO usradmin (username,passwd)values (:a,:b)', ('admin', '4c635087df1041bd13681ee3c6eb04d5'))
    conn.commit()
    print('USRADMIN表创建成功')

#判断INPUT_SELECT是否存在，如果不存在创建
if tabel2 in array:
    pass
else:
    cursor.execute('create table input_select (dev_ID integer PRIMARY KEY, description text, free integer)')
    conn.commit()
    # rows = [(1, '测试输入1', 1), (2, '测试输入2', 1), (3, '测试输入3', 1)]
    # sql = "insert into input_select (dev_id,description,free) values (:a,:b,:o)"
    # cursor.executemany(sql, rows)
    # conn.commit()
    print('INPUT_SELECT表创建成功')

#判断OUTPUT_LIST是否存在，如果不存在创建
if tabel3 in array:
    pass
else:
    cursor.execute('create table output_list (id integer PRIMARY KEY, name text)')
    conn.commit()
    # rows = [(1, '测试输出1'), (2, '测试输出2'), (3, '测试输出3')]
    # sql = 'insert into output_list (id,name) values (:a,:b)'
    # cursor.executemany(sql, rows)
    # conn.commit()
    print('OUTPUT_LIST表创建成功')

#判断KEYS_SET是否存在，如果不存在创建
if tabel4 in array:
    pass
else:
    sql = "create table keys_set (inputID text PRIMARY KEY ,inputName text,ip text,description text,keyName varchar (1000),key1 varchar (2000),key2 varchar(2000),key3 varchar(2000),key4 varchar(2000),key5 varchar(2000),key6 varchar(2000),key7 varchar(2000),key8 varchar(2000),key9 varchar(2000),key10 varchar(2000),key11 varchar(2000),key12 varchar(2000),key1id varchar (2000),key2id varchar(2000),key3id varchar(2000),key4id varchar(2000),key5id varchar(2000),key6id varchar(2000),key7id varchar(2000),key8id varchar(2000),key9id varchar(2000),key10id varchar(2000),key11id varchar(2000),key12id varchar(2000),status text)"
    cursor.execute(sql)
    conn.commit()
    print('KEYS_SET表创建成功')

# 判断TEMPLATE是否存在，如果不存在创建
if tabel5 in array:
    pass
else:
    sql = "create table template (name text,key1 varchar (2000),key2 varchar(2000),key3 varchar(2000),key4 varchar(2000),key5 varchar(2000),key6 varchar(2000),key7 varchar(2000),key8 varchar(2000),key9 varchar(2000),key10 varchar(2000),key11 varchar(2000),key12 varchar(2000),keyName varchar (1000),key1id varchar (2000),key2id varchar(2000),key3id varchar(2000),key4id varchar(2000),key5id varchar(2000),key6id varchar(2000),key7id varchar(2000),key8id varchar(2000),key9id varchar(2000),key10id varchar(2000),key11id varchar(2000),key12id varchar(2000))"
    cursor.execute(sql)
    conn.commit()
    print('TEMPLATE表创建成功')

# 判断TASK是否存在，如果不存在创建
if tabel6 in array:
    pass
else:

    sql = "create table task (name text ,taskmap varchar (1000))"
    cursor.execute(sql)
    conn.commit()
    print('TASK表创建成功')


# 判断WEB_STATUS是否存在，如果不存在创建
if tabel7 in array:
    pass
else:
    cursor.execute('create table web_status (id integer PRIMARY KEY AUTO_INCREMENT,ip text ,status text,port text)')
    conn.commit()
    print('WEB_STATUS表创建成功')


sql = " SELECT inputID,inputName,ip,status FROM keys_set"
cursor.execute(sql)
array = cursor.fetchall()
for i in array:
    i = list(i)
    status_dict[i[0]] = i
conn.close()
# 用户操作logger配置
userlogger = logging.getLogger("MULTIKEYS_SERVER_USER")
userlogger.setLevel(logging.INFO)
userfh = logging.FileHandler("./log/multikeys_server_user.log")
userfh.setLevel(logging.INFO)
userch = logging.StreamHandler()
userch.setLevel(logging.INFO)
formatter = logging.Formatter("%(asctime)s--%(name)s--%(levelname)s - %(message)s")
userch.setFormatter(formatter)
userfh.setFormatter(formatter)
userlogger.addHandler(userch)
userlogger.addHandler(userfh)
# 系统运行logger配置
syslogger = logging.getLogger("MULTIKEYS_SERVER_SYSTEM")
syslogger.setLevel(logging.INFO)
sysfh = logging.FileHandler("./log/multikeys_server_system.log")
sysfh.setLevel(logging.INFO)
sysch = logging.StreamHandler()
sysch.setLevel(logging.INFO)
formatter = logging.Formatter("%(asctime)s--%(name)s--%(levelname)s - %(message)s")
sysch.setFormatter(formatter)
sysfh.setFormatter(formatter)
syslogger.addHandler(sysch)
syslogger.addHandler(sysfh)





# 获取首页信息
def main(request):
    if request.method == 'GET':
        conn = STPython.connect(user=database['default']['NAME'], password=database['default']['PASSWD'], dsn=database['default']['DSN'])
        cursor = conn.cursor()
        # 获取设备数量
        sql = "SELECT count(*) FROM keys_set"
        cursor.execute(sql)
        num = cursor.fetchone()

        # 获取已配置列表
        sql = " SELECT inputID,inputName,ip,status FROM keys_set"
        cursor.execute(sql)
        array = cursor.fetchall()

        for i in array:
            i = list(i)

            status_dict[i[0]][1] = i[1]
        conn.close()

        return render(request, 'system/main.html', {'setnum': num[0], 'form': list(status_dict.values())})


# 获取已配置列表
def configed(request):
    if request.method == 'GET':
        conn = STPython.connect(user=database['default']['NAME'], password=database['default']['PASSWD'], dsn=database['default']['DSN'])
        cursor = conn.cursor()
        sql = " SELECT inputName,ip,description,inputID FROM keys_set"
        cursor.execute(sql)
        form_configed = cursor.fetchall()
        conn.close()
        return render(request, 'system/configed.html', {'form': form_configed})


# 获取未配置列表
def free(request):
    conn = STPython.connect(user=database['default']['NAME'], password=database['default']['PASSWD'], dsn=database['default']['DSN'])
    cursor = conn.cursor()
    if request.method == 'GET':
        sql = " SELECT dev_ID,description FROM input_select WHERE free = 1"
        cursor.execute(sql)
        form_free = cursor.fetchall()
        conn.close()
        return render(request, 'system/free.html', {'form': form_free})


# 获取当前配置信息
def config(request):
    conn = STPython.connect(user=database['default']['NAME'], password=database['default']['PASSWD'], dsn=database['default']['DSN'])
    key_list = range(1, 13)
    key_name_list = []
    for index in range(1, 13):
        key_name_list.append("按键" + str(index))
    if request.method == 'POST':
        form = ConfigForm(request.POST)
        if form.is_valid():
            info_dict = form.cleaned_data
            status = info_dict['status']
            cursor = conn.cursor()
            sql = " SELECT name,id FROM output_list "
            cursor.execute(sql)
            output_name = cursor.fetchall()
            sql = " SELECT name FROM template"
            cursor.execute(sql)
            form_template = cursor.fetchall()
            dict_keyname = {'1': info_dict['key1'], '2': info_dict['key2'], '3': info_dict['key3'], '4': info_dict['key4'],
                            '5': info_dict['key5'], '6': info_dict['key6'], '7': info_dict['key7'], '8': info_dict['key8'],
                            '9': info_dict['key9'], '10': info_dict['key10'], '11': info_dict['key11'], '12': info_dict['key12']}
            # 新建按键配置
            if status == 'new':
                data = json.dumps([' ', ' '])
                sql = "INSERT INTO keys_set (inputID, inputName, ip, description, keyName, status, " + \
                      "key1, key2, key3, key4, key5, key6, key7, key8, key9, key10, key11, key12," + \
                      "key1id, key2id, key3id, key4id, key5id, key6id, key7id, key8id, key9id, key10id, key11id, key12id) " + \
                      "values('" + info_dict['id'] + "','" + info_dict['name'] + "','" + info_dict['ip'] + "','" + info_dict['description'] + "','" + \
                      json.dumps(dict_keyname, ensure_ascii=False) + "','off'," + \
                      "'" + data + "','" + data + "','" + data + "','" + data + "','" + data + "','" + data + "','" + data + "','" + data + \
                      "','" + data + "','" + data + "','" + data + "','" + data + "','" + data + "','" + data + "','" + data + "','" + data + \
                      "','" + data + "','" + data + "','" + data + "','" + data + "','" + data + "','" + data + "','" + data + "','" + data + "')"
                try:
                    cursor.execute(sql)
                except Exception as e:
                    conn.close()
                    return render(request, 'system/config.html', {'name': info_dict['name'], 'id': info_dict['id'], 'form': form, 'status': 'new', 'alter': 'error'})
                else:
                    conn.commit()
                    sql = " UPDATE input_select SET free = 0 WHERE dev_ID = '"+info_dict['id']+"'"
                    cursor.execute(sql)
                    conn.commit()
                    conn.close()
                    status_dict[info_dict['id']] = [info_dict['id'], info_dict['name'], info_dict['ip'], 'off']
                    key_name_list = list(dict_keyname.values())
                    for index,keyname in enumerate(key_name_list):
                        if keyname == '':

usradmin/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from .forms import NameForm
from multikeys import settings
database = settings.DATABASES
# Create your views here.

def login(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            return HttpResponseRedirect('/system/main.html')
        else:
            return render(request, 'usradmin/login.html', {'form': form})
    else:
        form = NameForm()
    return render(request, 'usradmin/login.html', {'form': form})

templates/system/config.html
{% extends "base.html" %}

{% load static %}

{% block title %}编辑设备配置{% endblock %}

{% block css %}
<link href="{% static  "system/css/config.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="alert alert-danger" role="alert" id="myalter" style="display: none">
    <button type="button" class="close" id="close">
      <span aria-hidden="true">&times;</span>
    </button>
  <strong>IP地址不合法</strong> 请重新输入。
</div>

<div class="alert alert-danger" role="alert" id="myalter1" style="display: none">
    <button type="button" class="close" id="close1">
      <span aria-hidden="true">&times;</span>
    </button>
  <strong>该IP已经被注册</strong> 请重新输入。
</div>

<div class="row sparse"><label class="head">设备配置&nbsp&nbsp&nbsp&nbsp</label></div>
<form method="post" onsubmit="return checkIP()" id="form1">
{% csrf_token %}
    <div class="row sparse_min">
        <div class="col-md-5 col-md-offset-1">
            <label>输入接口ID:&nbsp&nbsp</label>{{ form.id }}
        </div>
        <div class="col-md-6">
            <label>输入接口名称:&nbsp&nbsp</label>{{ form.name }}
        </div>
    </div>
    <div class="row sparse_min">
        <div class="col-md-5 col-md-offset-1">
            <label>多按键设备IP<span class="red">*</span>:&nbsp&nbsp</label>{{ form.ip }}
        </div>
        <div class="col-md-6">
            <label>多按键设备描述:&nbsp&nbsp</label>{{ form.description }}
        </div>
    </div>
    <div class="row sparse_min">
        <div class="col-md-5 col-md-offset-1">
            <label>预设 1 按键名称:&nbsp&nbsp</label>{{ form.key1 }}
        </div>
        <div class="col-md-6">
            <label>预设 2 按键名称:&nbsp&nbsp</label>{{ form.key2 }}
        </div>
    </div>
    <div class="row sparse_min">
        <div class="col-md-5 col-md-offset-1">
            <label>预设 3 按键名称:&nbsp&nbsp</label>{{ form.key3 }}
        </div>
        <div class="col-md-6">
            <label>预设 4 按键名称:&nbsp&nbsp</label>{{ form.key4 }}
        </div>
    </div>
    <div class="row sparse_min">
        <div class="col-md-5 col-md-offset-1">
            <label>预设 5 按键名称:&nbsp&nbsp</label>{{ form.key5 }}
        </div>
        <div class="col-md-6">
            <label>预设 6 按键名称:&nbsp&nbsp</label>{{ form.key6 }}
        </div>
    </div>
    <div class="row sparse_min">
        <div class="col-md-5 col-md-offset-1">
            <label>预设 7 按键名称:&nbsp&nbsp</label>{{ form.key7 }}
        </div>
        <div class="col-md-6">
            <label>预设 8 按键名称:&nbsp&nbsp</label>{{ form.key8 }}
        </div>
    </div>
    <div class="row sparse_min">
        <div class="col-md-5 col-md-offset-1">
            <label>预设 9 按键名称:&nbsp&nbsp</label>{{ form.key9 }}
        </div>
        <div class="col-md-6">
            <label>预设10按键名称:&nbsp&nbsp</label>{{ form.key10 }}
        </div>
    </div>
    <div class="row sparse_min">
        <div class="col-md-5 col-md-offset-1">
            <label>预设11按键名称:&nbsp&nbsp</label>{{ form.key11 }}
        </div>
        <div class="col-md-6">
            <label>预设12按键名称:&nbsp&nbsp</label>{{ form.key12 }}
        </div>
    </div>
    <div style="display: none;">{{ form.status }}</div>
    <div class="row sparse">
        <div class="col-md-4 col-md-offset-8">
            <input type="submit" value="保存并进入按键配置" class="btn btn-primary">
        </div>
    </div>
</form>


{% endblock %}

{% block js %}
<script type="text/javascript">
    $('a#flow').attr('aria-expanded','true');
    $('div#collapseExample').attr('class','collapse in');
    $('input#id_id').val('{{ id }}');
    $('input#id_name').val('{{ name }}');
    $('button#close').click(function () {
        $('#myalter').attr('style','display:none')
    });

    $('button#close1').click(function () {
        $('#myalter1').attr('style','display:none')
    });

    if('{{ alter }}'=='error'){
        $('#myalter1').attr('style','display:block')
    }

    if('{{ status }}'=='edit') {
        $('li#edit').attr('style','border-color: #23527c;');
        $('li#edit>a').attr('style','text-decoration: none;background-color: #eee;color: #23527c;');
        $('li#dev_configed > a').attr('style','color: #efb041;padding-left: 30px;');
        $('input#id_status').val('edit');
    } else {
        $('li#dev_free > a').attr('style','color: #efb041;padding-left: 30px;');
        $('input#id_status').val('new');
    }

    if(('{{ status }}' === 'edit') && ('{{ alter }}' !== 'error')) {
        $('input#id_ip').val('{{ dict.ip }}');
        $('input#id_description').val('{{ dict.description }}');
        $('input#id_key1').val('{{ dict.key1 }}');
        $('input#id_key2').val('{{ dict.key2 }}');
        $('input#id_key3').val('{{ dict.key3 }}');
        $('input#id_key4').val('{{ dict.key4 }}');
        $('input#id_key5').val('{{ dict.key5 }}');
        $('input#id_key6').val('{{ dict.key6 }}');
        $('input#id_key7').val('{{ dict.key7 }}');
        $('input#id_key8').val('{{ dict.key8 }}');
        $('input#id_key9').val('{{ dict.key9 }}');
        $('input#id_key10').val('{{ dict.key10 }}');
        $('input#id_key11').val('{{ dict.key11 }}');
        $('input#id_key12').val('{{ dict.key12 }}');
    }

    function checkIP() {
        obj = document.getElementById("id_ip").value;
        //ip地址
        var exp=/^(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])$/;
        var reg = obj.match(exp);
        if(reg==null) {
            $('#myalter').attr('style','display:block')
            return false;
        }
        else {
            return true;
        }
    }

</script>
{% endblock %}

templates/system/free.html
{% extends "base.html" %}

{% load static %}

{% block title %}新增设备配置{% endblock %}

{% block css %}
<link href="{% static  "system/css/free.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="row sparse"><label class="head">新增设备配置&nbsp&nbsp&nbsp&nbsp</label></div>
    <div class="row sparse" id="search_bar">
        <div class="col-md-3">
            <label>可用多按键设备列表</label>
        </div>
        <div class="col-md-7">
            <input type="text" placeholder="按名称关键字搜索" id="search_info">
            <button class="btn btn-primary" id="search_button">
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span> 搜索</button>
        </div>
        <div class="col-md-3"></div>
    </div>
    <div class="col-md-12">
        <div id="table_box">
            <table class="table table-hover table-condensed table-striped" id="free_table">
                <colgroup>
                    <col style="width: 40px"><col style="width: 70px"><col style="width: 70%"><col style="width: 100px">
                </colgroup>
                <thead>
                    <tr>
                        <th>序号</th>
                        <th>输入设备ID</th>
                        <th>名称</th>
                        <th class="download">绑定多按键设备</th>
                    </tr>
                </thead>
            </table>
        </div>
        <div id="free_table_box">
            <table class="table table-hover table-condensed table-striped" id="free_table_body">
                <colgroup>
                    <col style="width: 40px"><col style="width: 70px"><col style="width: 70%"><col style="width: 100px">
                </colgroup>
                <tbody >
                {% for form in form %}
                    <tr id="id{{ forloop.counter }}">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ form.0 }}</td>
                        <td id="name_{{ forloop.counter }}">{{ form.1 }}</td>
                        <td class="download">
                            <a class="btn config" href="/system/config.html?id={{ form.0 }}&name={{ form.1 }}&status=new">
                                <span class="glyphicon glyphicon-import" aria-hidden="true" ></span>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>


{% endblock %}

{% block js %}
<script type="text/javascript">
    $('a#flow').attr('aria-expanded','true');
    $('div#collapseExample').attr('class','collapse in');
    $('#search_button').click(function () {
        var text = $('#search_info').val()
        for(i = 1;i<={{form|length}};i++){
            var file_name = $('#name_'+ i).text()
            {#file_name=file_name.replace(".html","");#}
            if (file_name.indexOf(text) == -1){
                $('#id'+ i).attr('style','display:none')
            }else {
                var str = '<span style="background-color:#eec805">'+text+'</span>';
                $('#name_'+ i).html($('#name_'+ i).text().replace(text,str));
            }
        }
    })
    $("#search_info").blur(function () {
        var text = $(this).val()
        if(text == ''){
            for(i = 1;i<={{form|length}};i++){
                $('#id'+ i).removeAttr('style')
                $('#id_'+ i + '>span').removeAttr('style')
            }
        }
    })
</script>
{% endblock %}